# Generated by Django 6.0.2 on 2026-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_update_patient_and_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uhid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
