# Generated by Django 6.0.2 on 2026-02-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_uhid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhaar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhaar_token',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
