# Generated by Django 6.0.2 on 2026-02-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_update_report_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-uploaded_at"]},
        ),
    ]
