# Generated by Django 6.0.2 on 2026-02-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_add_access_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportaccessaudit',
            new_name='reports_rep_report__172f28_idx',
            old_name='reports_rep_report_idx',
        ),
        migrations.RenameIndex(
            model_name='reportaccessaudit',
            new_name='reports_rep_user_id_ae6b0b_idx',
            old_name='reports_rep_user_idx',
        ),
    ]
